### ISSUE TITLE
`PlayableNode.GetContentType()' is marked as an override but no suitable method found to override

### ISSUE THREAD

**Issue by Jaredrhd** [Unity-Technologies/graph-visualizer#6]
Hello. I downloaded the 2017.1.2 and imported the package into my project. I than received the following error.

Assets/graph-visualizer-2017.1-2/Assets/GraphVisualizer/Editor/PlayableGraphVisualizer.cs(47,26): error CS0115: `PlayableNode.GetContentType()' is marked as an override but no suitable method found to override.

Not sure if this is my mistake though and I haven't seen a workaround yet?

**Comment by romainf-unity** [comment]
Looking at your error, it should override the method in GraphVisualizer/Editor/Graph/Node.cs, but since the GraphVisualizer isn't in its own namespace, it might be taking another `Node` definition from your project...

Definitely, I should put everything in a distinct namespace.

As a workaround, could you try renaming `Node` to `GVNode` and in all the references in GraphVisualizer/ ? If I'm right, that should do it.

**Comment by Jaredrhd** [comment]
Renaming Node to GVNode worked thanks. I completely forgot about my other Script called Node.

**Comment by romainf-unity** [comment]
Thanks a lot for testing the workaround ;)
I'll fix the bug as soon as possible!
